import {
  ArrowLeftRight,
  Baby,
  Banknote,
  Beer,
  Bike,
  Book,
  Briefcase,
  Bus,
  Car,
  Circle,
  CircleHelp,
  Clapperboard,
  Coffee,
  Cpu,
  CreditCard,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  Martini,
  Music,
  Palmtree,
  PawPrint,
  PiggyBank,
  Pill,
  Plane,
  Receipt,
  Scissors,
  Shapes,
  ShoppingBag,
  ShoppingCart,
  Shirt,
  Smartphone,
  Sparkles,
  Stethoscope,
  Train,
  TrendingUp,
  Utensils,
  Wallet,
  Wine,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const ICON_LIBRARY: Record<string, LucideIcon> = {
  home: Home,
  utensils: Utensils,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  coffee: Coffee,
  martini: Martini,
  wine: Wine,
  beer: Beer,
  clapperboard: Clapperboard,
  music: Music,
  "gamepad-2": Gamepad2,
  shirt: Shirt,
  sparkles: Sparkles,
  scissors: Scissors,
  heart: Heart,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  bike: Bike,
  cpu: Cpu,
  laptop: Laptop,
  smartphone: Smartphone,
  plane: Plane,
  train: Train,
  bus: Bus,
  car: Car,
  fuel: Fuel,
  palmtree: Palmtree,
  receipt: Receipt,
  "credit-card": CreditCard,
  wallet: Wallet,
  landmark: Landmark,
  banknote: Banknote,
  "piggy-bank": PiggyBank,
  "arrow-left-right": ArrowLeftRight,
  "trending-up": TrendingUp,
  briefcase: Briefcase,
  book: Book,
  "graduation-cap": GraduationCap,
  "paw-print": PawPrint,
  baby: Baby,
  wrench: Wrench,
  gift: Gift,
  shapes: Shapes,
  "circle-help": CircleHelp,
  circle: Circle,
};

export const DEFAULT_ICON = "shapes";

export function getCategoryIcon(icon: string | null): LucideIcon {
  return (icon && ICON_LIBRARY[icon]) || ICON_LIBRARY[DEFAULT_ICON];
}
